# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.IntegerField()),
                ('user', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
