# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gclick',
            field=models.IntegerField(default=0, verbose_name='人气'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gdigest',
            field=models.CharField(max_length=100, verbose_name='商品摘要'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gimage',
            field=models.ImageField(upload_to='goods', verbose_name='上传图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ginfo',
            field=tinymce.models.HTMLField(verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gkucun',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtime',
            field=models.DateTimeField(verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtj',
            field=models.BooleanField(default=False, verbose_name='新品推荐'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='500g', max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='商品类别'),
        ),
    ]
